import { Product } from "@/types/product"

export const products: Product[] = [
  {
    id: 1,
    title: "ScreenWatch",
    price: 20,
    category: "wearables",
    image: "/products/1.png",
    description: "Smartwatch with lightweight design and health tracking",
    rating: { rate: 4.5, count: 120 },
  },
  {
    id: 2,
    title: "SmartMouse",
    price: 80,
    category: "peripherals",
    image: "/products/2.png",
    description: "Ergonomic wireless mouse for everyday productivity",
    rating: { rate: 4.8, count: 250 },
  },
  {
    id: 3,
    title: "Smart Laser",
    price: 20,
    category: "accessories",
    image: "/products/3.png",
    description: "Compact laser pointer for presentations",
    rating: { rate: 4.5, count: 120 },
  },
  {
    id: 4,
    title: "Holo Laptop",
    price: 1200,
    category: "laptop",
    image: "/products/4.png",
    description: "Slim laptop with immersive high resolution display",
    rating: { rate: 4.6, count: 98 },
  },
  {
    id: 5,
    title: "AirSound Pro",
    price: 55,
    category: "audio",
    image: "/products/5.png",
    description: "Wireless earbuds with active noise cancellation",
    rating: { rate: 4.6, count: 180 },
  },
  {
    id: 6,
    title: "MechaKey X",
    price: 95,
    category: "peripherals",
    image: "/products/6.png",
    description: "Mechanical keyboard with RGB backlight",
    rating: { rate: 4.7, count: 210 },
  },
  {
    id: 7,
    title: "VisionCam 4K",
    price: 70,
    category: "peripherals",
    image: "/products/7.png",
    description: "4K webcam for streaming and meetings",
    rating: { rate: 4.4, count: 140 },
  },
  {
    id: 8,
    title: "PowerHub 8-in-1",
    price: 35,
    category: "accessories",
    image: "/products/8.png",
    description: "USB C multiport hub for charging and data transfer",
    rating: { rate: 4.3, count: 95 },
  },
  {
    id: 9,
    title: "NanoPad S",
    price: 45,
    category: "peripherals",
    image: "/products/9.png",
    description: "Portable touchpad with gesture support",
    rating: { rate: 4.2, count: 76 },
  },
  {
    id: 10,
    title: "UltraDisplay 27",
    price: 299,
    category: "peripherals",
    image: "/products/10.png",
    description: "27 inch QHD monitor with vivid color accuracy",
    rating: { rate: 4.7, count: 188 },
  },
  {
    id: 11,
    title: "ChargeDock Trio",
    price: 49,
    category: "accessories",
    image: "/products/11.png",
    description: "3 in 1 wireless charging dock for daily devices",
    rating: { rate: 4.3, count: 112 },
  },
  {
    id: 12,
    title: "GameBox Mini",
    price: 199,
    category: "gaming",
    image: "/products/12.png",
    description: "Compact console for casual and retro gaming",
    rating: { rate: 4.5, count: 160 },
  },
  {
    id: 13,
    title: "DeskLight Aura",
    price: 39,
    category: "accessories",
    image: "/products/13.png",
    description: "Adjustable desk lamp with eye comfort mode",
    rating: { rate: 4.4, count: 89 },
  },
  {
    id: 14,
    title: "SoundBar Beam",
    price: 129,
    category: "audio",
    image: "/products/14.png",
    description: "Compact soundbar with clear vocal enhancement",
    rating: { rate: 4.6, count: 134 },
  },
  {
    id: 15,
    title: "PocketSSD 1TB",
    price: 110,
    category: "storage",
    image: "/products/15.png",
    description: "High speed external SSD with durable body",
    rating: { rate: 4.8, count: 202 },
  },
  {
    id: 16,
    title: "RouterWave AX",
    price: 145,
    category: "networking",
    image: "/products/16.png",
    description: "WiFi 6 router with stable multi device coverage",
    rating: { rate: 4.5, count: 117 },
  },
  {
    id: 17,
    title: "PenTab Create",
    price: 89,
    category: "peripherals",
    image: "/products/17.png",
    description: "Drawing tablet for digital art and design work",
    rating: { rate: 4.4, count: 73 },
  },
  {
    id: 18,
    title: "ClipMic Go",
    price: 32,
    category: "audio",
    image: "/products/18.png",
    description: "Clip on microphone for calls and content creation",
    rating: { rate: 4.2, count: 64 },
  },
  {
    id: 19,
    title: "PhoneStand Flex",
    price: 18,
    category: "accessories",
    image: "/products/19.png",
    description: "Foldable phone stand for desk and travel use",
    rating: { rate: 4.1, count: 58 },
  },
  {
    id: 20,
    title: "AirCool Pad",
    price: 42,
    category: "laptop",
    image: "/products/20.png",
    description: "Laptop cooling pad with silent high airflow fans",
    rating: { rate: 4.3, count: 81 },
  },
]